# Generated by Django 3.2.2 on 2021-05-08 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210508_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 46, 1, 394626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 16, 1, 392789)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 16, 1, 394075)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 16, 1, 389159)),
        ),
    ]
