# Generated by Django 3.2.2 on 2021-05-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210506_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
