# Generated by Django 3.2.2 on 2021-05-14 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210508_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 7, 53, 47, 391833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 12, 23, 47, 389955)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 12, 23, 47, 391288)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 12, 23, 47, 386425)),
        ),
        migrations.CreateModel(
            name='all_users_chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 14, 7, 53, 47, 392408, tzinfo=utc))),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.all_users_chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
