# Generated by Django 3.2.2 on 2021-05-07 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210507_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 38, 12, 69118)),
        ),
        migrations.AlterField(
            model_name='followers',
            name='another_user',
            field=models.ManyToManyField(related_name='another_user_followers', to='app1.User'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 38, 12, 70412)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 38, 12, 66283)),
        ),
        migrations.CreateModel(
            name='followering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_user', models.ManyToManyField(related_name='another_user_following', to='app1.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
