# Generated by Django 3.2.2 on 2021-05-07 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210507_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 39, 59, 847794)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 39, 59, 849083)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 39, 59, 844961)),
        ),
        migrations.DeleteModel(
            name='followering',
        ),
        migrations.AddField(
            model_name='following',
            name='another_user',
            field=models.ManyToManyField(related_name='another_user_following', to='app1.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
