# Generated by Django 3.2.2 on 2021-05-08 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210508_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_users_chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 16, 14, 11, 563843)),
        ),
        migrations.AlterField(
            model_name='all_users_chat',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 16, 14, 11, 562004)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 16, 14, 11, 563333)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 16, 14, 11, 559144)),
        ),
    ]
